### ISSUE TITLE
유저스토리: 작성자만 글을 수정/삭제할 수 있어야 한다.

### ISSUE THREAD

**Issue by expert0226** [clojure-study/guestbook#18]
- 로그인 사용자와 글의 작성자를 비교
- 같을 때만 [수정] / [삭제] 버튼 노출.. .노출.. 노출.. 여름이다.
- 한철희님이 시켰어요.

**Comment by manmyung** [comment]
https://github.com/clojure-study/guestbook/pull/22
에서 해결되었습니다.
