### ISSUE TITLE
회원 가입시 캡차를 사용한다. 

### ISSUE THREAD

**Issue by yangwansu** [clojure-study/guestbook#26]
회원 가입시 캡차를 사용하여 자동 매크로를 이용한 악의 적인 회원가입을 막는다.

**Comment by yangwansu** [comment]
https://ko.wikipedia.org/wiki/CAPTCHA

**Comment by lispro06** [comment]
구글에서 제공하는 reCAPTCHA API 가 있습니다. 저도 아직 적용은 안 해 봤지만, 사용해봤을 때, 숫자 입력보다는 나은 듯.

**Comment by yangwansu** [comment]
@lispro06  오 좋네요 .. 이것도 한번해봐야겠습니다. 감사합니다.

**Comment by yangwansu** [comment]
여기에서 일차적으로 이미지로 간단하게 넣어보았습니다. https://github.com/clojure-study/guestbook/commit/869f1aa250db7ffc341ea045789249b45499f34f

아직 이슈는 닫지 않고 구글 reCAPTCHA 를 한번 다시 도전해보아야겠네요

**Comment by yangwansu** [comment]
recaptcha 적용완료
