### ISSUE TITLE
방명록 글 Enter 처리

### ISSUE THREAD

**Issue by expert0226** [clojure-study/guestbook#31]
입력 시 Enter 가 있으면 보여줄 때 라인을 바꾸어서 보여주는 기능 필요.

**Comment by dreamofsnail** [comment]
Participating이 이런거 였군요^^; Assign 하셨다고 해서 한참 찾았네요ㅋ (UI랑 단어들이 익숙하지 않네요; 레드마인 같은 느낌일줄 알았는데;;) 여튼 일단 해보겠습니다!!

**Comment by yangwansu** [comment]
와우 완료되었네요?? ^^; 배포하도록 할게요

**Comment by dreamofsnail** [comment]
중간에 branch 테러도 하고;;; 아직 미숙해서 뭘 더 건드릴 수 있을지 모르겠네요ㅋ
