### ISSUE TITLE
데이터베이스 변경하기

### ISSUE THREAD

**Issue by soulawaker** [clojure-study/guestbook#49]
h2에서 postgreSQL로 변경하기

**Comment by soulawaker** [comment]
새로운 브랜치 postgres에 데이터베이스 변경 부분을 적용하여 올렸습니다.
project.clj에서 :database-url 부분을 찾아 host:port/schema_name?user=사용자이름&password=비번" 부분을 맞춰서 적어 주시면 됩니다.

**Comment by yangwansu** [comment]
우왕 감사감사

**Comment by soulawaker** [comment]
변경 완료
