### ISSUE TITLE
로컬에 PostgreSQL 설치하여 프로젝트에 연결하는 방법 README에 추가

### ISSUE THREAD

**Issue by manmyung** [clojure-study/guestbook#60]
프로젝트를 로컬에서 돌려보려고 하는데 PostgreSQL이 설치가 되어 있지 않아서 에러가 나네요.
PostgreSQL 경험이 없는 사람을 위해, 어떻게 설치하고 실행시켜 프로젝트에 연결하는지에 대한 안내를 README에 추가하면 좋을 것 같습니다.

저의 경우 맥인데 프로젝트 실행을 못하고 있어요ㅠㅠ
Postgre.app을 설치하여 실행은 시켰는데 "jdbc:postgresql://호스트이름(또는 주소):포트번호/데이터베이스이름?user=이름&password=비밀번호" 를 어떻게 지정해야 하는지 모르겠어요.

**Comment by expert0226** [comment]
쿨럭... 메일 보니 카톡 보낸 건 무시해 주삼...

https://en.wikibooks.org/wiki/Clojure_Programming/Examples/JDBC_Examples

문서내 검색어 "PostgreSQL"

2015년 9월 24일 오전 12:19, Manmyung Kim notifications@github.com님이 작성:

**Comment by manmyung** [comment]
README에 추가했습니다.
